services:
  simple-git-server:
    #platform:
    #  - linux/amd64
    #  - linux/arm64
    build:
      context: .
    # args:

    image: simple-git-server
    container_name: simple-git-server

    ports:
      - "8080:80"     # HTTP port
      - "2222:22"     # SSH port
      - "9989:9989"
      - "8010:8010"
    environment:
      GIT_ADMIN: gitolite
    cap_add:
      - sys_ptrace                          # Only here to help testing
    volumes:
      - /etc/localtime:/etc/localtime:ro    # Use host timezone
      - sshd:/etc/ssh/
      - gitolite-home:/var/lib/git/

volumes:
  sshd:
  gitolite-home:
