repos:
#  - remote-url: "https://github.com/bit-team/backintime.git"
#    remote-name: "github"
#    local-repo: "test/backintime.git"

#  - remote-url: "https://github.com/flathub/flathub.git"
#    remote-name: "github"
#    local-repo: "test/flathub.git"
