#!/bin/bash                                                                                                                                                                                                                                   

echo "`basename "$0"`: start"

RWD="$HOME/tmp/gitolite-admin-$RANDOM" # Repo Working Directory

echo "`basename "$0"`: clonig repo.."
git clone -b master $GL_REPO_BASE/gitolite-admin.git $RWD

cd $RWD
GIT_DIR="$RWD/.git"

if [ -f "$RWD/server/gitconfig" ]; then
  cp -v $RWD/server/gitconfig $HOME/.gitconfig
fi

if [ -f "$RWD/server/gitolite.rc" ]; then
  cp -v $RWD/server/gitolite.rc $HOME/.gitolite.rc
fi

if [ -f "$RWD/server/gitweb.conf" ]; then
  cp -v $RWD/server/gitweb.conf $HOME/gitweb.conf
fi

if [ -f "$RWD/server/master.cfg" ]; then
  sudo /etc/init.d/buildbot stop
  cp -v $RWD/server/master.cfg /var/lib/buildbot/master.cfg
  sudo /etc/init.d/buildbot start
fi

echo "`basename "$0"`: cleaning.."
cd "$HOME/tmp/"
rm -rf $RWD
                                                                                                                                                                                                                                              
echo "`basename "$0"`: end"    
