#!/bin/bash

# this script is used to manage the update for server-admin repo
# this can be used as example for other hooks

GL_COMMIT=$(git log --all -n 1 --format="%H")
SCRIPT_NAME=`basename "$0"`
export PATH="$HOME/bin/:$PATH"
RWD="$HOME/tmp/$GL_REPO-$RANDOM" # Repo Working Directory

echo "$SCRIPT_NAME: start"
echo "`basename "$0"`: clonig repo.."
git clone -b master $GL_REPO_BASE/$GL_REPO $RWD
cd $RWD
GIT_DIR="$RWD/.git"
git checkout $GL_COMMIT

if [[ -f $RWD/update-server.sh ]]; then
	./update-server.sh
else
	echo "`basename "$0"`: missing file 'update-server.sh'; skipping update..."
fi

echo "`basename "$0"`: cleaning.."
rm -rf $RWD

echo "`basename "$0"`: end"